#!/usr/bin/env python
# -*- mode: python -*-
#
# Copyright (C) 2005 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

if __name__ == '__main__':
    import os
    import sys
    import pwd
    import pygtk; pygtk.require('2.0');
    import gtk

    from sabayon import util
    from sabayon import config

    util.init_gettext ()

    def show_error_dialog (primary_text, secondary_text):
        errordialog = gtk.MessageDialog (None,
                                         gtk.DIALOG_DESTROY_WITH_PARENT,
                                         gtk.MESSAGE_ERROR,
                                         gtk.BUTTONS_CLOSE,
                                         primary_text)
        errordialog.format_secondary_text (secondary_text)
        errordialog.run ()
        errordialog.destroy ()

    if os.geteuid () != 0:
        show_error_dialog (_("Your account does not have permissions to run the Desktop User Profiles tool"),
                           _("Administrator level permissions are needed to run this program because it can "
                             "modify system files."))
        sys.exit (1)

    if os.environ.has_key ("SABAYON_SESSION_RUNNING"):
        show_error_dialog (_("Desktop User Profiles tool is already running"),
                           _("You may not use Desktop User Profiles tool from "
                             "within a profile editing session"))
        sys.exit (1)

    try:
        pwd.getpwnam (config.PROTOTYPE_USER)
    except KeyError, e:
        show_error_dialog (_("User account '%s' was not found") % config.PROTOTYPE_USER,
                           _("Sabayon requires a special user account '%s' to be present "
                             "on this computer. Try again after creating the account (using, "
                             "for example, the 'adduser' command)") % config.PROTOTYPE_USER)
        sys.exit (1)
                        
    from sabayon import profilesdialog
    
    dialog = profilesdialog.ProfilesDialog ()

    gtk.main ()
