#!/usr/bin/env python

#
# Copyright (C) 2005 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#

if __name__ == '__main__':
    import sys
    import gtk
    
    from sabayon import util
    from sabayon import sessionwindow

    util.init_gettext ()

    if len (sys.argv) != 4:
        sys.stderr.write (_("Usage: %s <profile-name> <profile-path> <display-number>\n") % sys.argv[0])
        sys.exit (1)

    (profile_name, profile_path, display_number) = sys.argv[1:4]

    window = sessionwindow.SessionWindow (profile_name, profile_path, display_number)
    window.window.connect ("destroy", gtk.main_quit)
    window.window.show ()

    gtk.main ()
